
dataset: "Quake_10x_Limb_Muscle"
task: "SC"
n_samples: 3909
n_classes: 6
seed: 5
lr: 0.0001
epochs: 500
tms: [5, 0]
dropout: 0.3
weight_decay: 0.1
hvg: 1000
lambda1: 100.0
lambda2: 0.1
k: 15
t: 0.1
in_dim: 3000
hid_dim: 1500
out_dim: 6
train: True
save_res: False