
dataset: "Quake_10x_Bladder"
task: "SC"
n_samples: 2500
n_classes: 4
seed: 5
lr: 0.005
epochs: 500
tms: [5, 0]
dropout: 0.5
weight_decay: 0.1
hvg: 1000
lambda1: 10.0
lambda2: 0.01
k: 15
t: 0.1
in_dim: 3000
hid_dim: 1500
out_dim: 4
train: True
save_res: False