
dataset: "Mouse_Brain_Anterior"
task: "ST"
n_samples: 2695
n_classes: 52
seed: 5
lr: 0.0001
epochs: 500
tms: [1, 0]
dropout: 0.3
weight_decay: 0.1
hvg: 1000
lambda1: 100.0
lambda2: 1.0
k: 3
t: 0.1
radius: 50
in_dim: 3000
hid_dim: 1500
out_dim: 100      # n_classes 50 100
train: False
showimg: False
save_res: False